### PR TITLE
Email receipt now displays attachment link

### LINKED ISSUE #13: Donation Receipt Attachments {attachmenturl} displays the tag in an email receipt, and not a link to the attachment
## Details
The email tag `{attachmenturl}` does not display a link to the attachment. It just shows the raw tag.

## Steps to replicate:
have the aforementioned plugins installed
upload and save a file in a single form in Donation Form Options >> Receipt Attachments
make a test donation
check the email receipt and see that the raw tag is displayed.

## Acceptance Criteria

 - [ ] `{attachmenturl}` email tag decode to expected value.
 - [ ] `{attachmenturl}` email tag  appear in email tag list below email message wp editor in email settings.

### PR DESCRIPTION
**Pull request by ravinderk**
## Description

Resolves #13 

I find out that we were loading the plugin on `init` action hook and email tags also register on `init` action hook, so this addon email tag does not register. I updated the code to load on `give_init`, so help addon to register email tags correctly.

## Visuals
MailHog 2021-09-22 at 10 16 51 PM

### CODE REVIEW

**Comment by digitalchild** [comment]
I can confirm that this is tested and working.

**Comment by JasonTheAdams** [comment]
Thank  you for confirming, @digitalchild! 🙌

**Review by kjohnson — APPROVED** [review]
Good to see `$payment->total` used instead of accessing donation meta and decoding, etc.

**Comment by kjohnson** [comment]
@ravinderk I added a CHANGELOG.md and merged this PR locally (since the branch was off of your personal fork).

**Pull request merged**
